import Icons from "@/components/globals/icons";

export const apiUrl = process.env.NEXT_PUBLIC_API_URL;

export const perks = [
  {
    icon: Icons.auth,
    title: "Sign Up",
    info: "Create your free account to get started with Formix.",
  },
  {
    icon: Icons.customize,
    title: "Customize",
    info: "Choose a theme, font, and input types to tailor your forms.",
  },
  {
    icon: Icons.launch,
    title: "Launch",
    info: "Publish your forms and share them effortlessly with your audience.",
  },
];

export const features = [
  {
    icon: Icons.bolt,
    title: "Fast Setup",
    info: "Get your forms up and running in minutes with our user-friendly builder.",
  },
  {
    icon: Icons.palette,
    title: "Customizable Themes",
    info: "Select from a variety of stunning themes and personalize them for your brand.",
  },
  {
    icon: Icons.code,
    title: "Code Generation",
    info: "Automatically generate code for your forms, making integration a breeze.",
  },
  {
    icon: Icons.dashboard,
    title: "Entry Dashboard",
    info: "Easily manage and track submissions through an intuitive dashboard.",
  },
  {
    icon: Icons.server,
    title: "Seamless Integration",
    info: "Integrate with backend solutions like Prisma and Supabase for efficient data management.",
  },
  {
    icon: Icons.monitor,
    title: "Priority Support",
    info: "Get assistance whenever you need it, ensuring your form-building experience is smooth.",
  },
];
export const pricingCards = [
  {
    title: "Free Tier",
    description: "Great for trying out Formix with basic features.",
    price: "Free",
    duration: "",
    highlight: "Key features",
    buttonText: "Start for free",
    features: ["Limited forms", "1 Team member", "Basic customization"],
    priceId: "",
  },
  {
    title: "Pro Plan",
    description: "Unlock advanced features and greater customization.",
    price: "$19",
    duration: "month",
    highlight: "Key features",
    buttonText: "Upgrade to Pro",
    features: [
      "Unlimited forms",
      "5 Team members",
      "Advanced customization tools",
      "Full code generation",
    ],
    priceId: "price_1OYxkqFj9oKEERu1KfJGWxgN",
  },
  {
    title: "Enterprise Plan",
    description: "Perfect for teams needing extensive features and support.",
    price: "$99",
    duration: "month",
    highlight: "Everything in Pro, plus",
    buttonText: "Upgrade to Enterprise",
    features: [
      "Unlimited forms",
      "Unlimited Team members",
      "Custom branding",
      "24/7 priority support",
    ],
    priceId: "price_1OYxkqFj9oKEERu1NbKUxXxN",
  },
];

export const bentoCards = [
  {
    title: "Start with Inspiration",
    info: "Explore our library of pre-designed templates to kickstart your form creation.",
    imgSrc: "/assets/bento-1.svg",
    alt: "Inspiration for form creation",
  },
  {
    title: "AI Assists Your Vision",
    info: "Let our intelligent AI suggest the best options based on your goals.",
    imgSrc: "/assets/bento-1.svg",
    alt: "AI assistance for form building",
  },
  {
    title: "Drag & Drop Customization",
    info: "Easily personalize your forms with our intuitive drag-and-drop editor.",
    imgSrc: "/assets/bento-1.svg",
    alt: "Website customization with drag and drop",
  },
  {
    title: "Launch & Shine Online",
    info: "Publish your forms with a single click and engage your audience instantly.",
    imgSrc: "/assets/bento-1.svg",
    alt: "Form launch and publication",
  },
];

export const reviews = [
  {
    name: "Alice",
    username: "@alice",
    body: "Formix has transformed how I create forms. It's intuitive and efficient!",
  },
  {
    name: "Bob",
    username: "@bob",
    body: "I love the customization options. I can make forms that truly reflect my brand.",
  },
  {
    name: "Charlie",
    username: "@charlie",
    body: "The dashboard is so helpful for tracking submissions. Highly recommend!",
  },
  {
    name: "Dana",
    username: "@dana",
    body: "Creating forms has never been easier. Formix is a game changer!",
  },
  {
    name: "Eve",
    username: "@eve",
    body: "Fantastic experience! The support team is responsive and helpful.",
  },
  {
    name: "Frank",
    username: "@frank",
    body: "I appreciate the AI suggestions. They save me so much time.",
  },
];

export const themes: Theme[] = [
  {
    id: "light-leaves",
    name: "Light Leaves",
    backgroundImage: "/bg/light-leaves.png",
    textColor: "text-gray-800",
    backgroundColor: "bg-white",
    buttonColor: "bg-gray-800 ",
    buttonText: "text-white",
    borderColor: "border-gray-400",
    placeholderColor: "placeholder:text-gray-600",
    checkboxChecked: "bg-gray-200/50 border-gray-600",
    checkboxUnchecked: "bg-white border-gray-400",
    checkboxText: "text-gray-800",
    okButton: "bg-gray-800 text-white",
  },
  {
    id: "light-pattern",
    name: "Light Pattern",
    backgroundImage: "/bg/light-pattern.png",
    textColor: "text-gray-800",
    backgroundColor: "bg-white",
    buttonColor: "bg-gray-600/30 text-gray-600",
    buttonText: "text-white",
    borderColor: "border-gray-300",
    placeholderColor: "placeholder:text-gray-600",
    checkboxChecked: "bg-gray-200 border-gray-600",
    checkboxUnchecked: "bg-gray-100 border-gray-400",
    checkboxText: "text-gray-800",
    okButton: "bg-gray-800 text-white",
  },
  {
    id: "light-gradient-1",
    name: "Light Gradient 1",
    backgroundImage: "/bg/light-gradient1.png",
    textColor: "text-[#e53757]",
    backgroundColor: "bg-white",
    buttonColor: "bg-[#e53757]",
    buttonText: "text-white",
    borderColor: "border-[#e53757]",
    placeholderColor: "placeholder:text-[#e53757]/30",
    checkboxChecked: "bg-[#e53757]/10  border-[#e53757]",
    checkboxUnchecked: "bg-transparent border-[#e53757]/40",
    checkboxText: "text-gray-800 ",
    okButton: "bg-[#e53757] text-white",
  },
  {
    id: "blue-medical",
    name: "Medical",
    backgroundImage: "/bg/blue.png",
    textColor: "text-gray-900",
    backgroundColor: "bg-cyan-400",
    buttonColor: "bg-[#4392bc]",
    buttonText: "text-white",
    borderColor: "border-[#4392bc]",
    placeholderColor: "placeholder:text-gray-600",
    checkboxChecked: "border-[#4392bc] bg-[#4392bc]/20 ",
    checkboxUnchecked: "bg-transparent border-[#4392bc]/40 ",
    checkboxText: "text-gray-900",
    okButton: "bg-white text-gray-300",
  },
  {
    id: "ocean-theme",
    name: "Ocean Theme",
    backgroundImage: "/bg/ocean.png",
    textColor: "text-white",
    backgroundColor: "bg-blue-800",
    buttonColor: "bg-[#00659B]",
    buttonText: "text-white",
    borderColor: "border-blue-300",
    placeholderColor: "placeholder:text-gray-300",
    checkboxChecked: "bg-[#00659B]/30 border-white/50 shadow-lg",
    checkboxUnchecked: " border-[#00659B]",
    checkboxText: "text-white",
    okButton: "bg-white text-gray-300",
  },

  {
    id: "yellow-orange-biege",
    name: "Yellow Orange Biege",
    backgroundImage: undefined,
    textColor: "text-[#D74B76]",
    backgroundColor: "bg-[#FFF7D1]",
    buttonColor: "bg-[#D74B76]",
    buttonText: "text-white",
    borderColor: "border-[#D74B76]/70",
    placeholderColor: "placeholder:text-[#D74B76]/40",
    checkboxChecked: "bg-[#F7C566]/10 border-[#FFB0B0] ",
    checkboxUnchecked: "border-[#D74B76]/40 ",
    checkboxText: "text-white",
    okButton: "bg-[#D74B76] text-white",
  },
  {
    id: "night-sky",
    name: "Night Sky",
    // backgroundImage: "/bg/night-sky.jpg",
    backgroundImage: "/bg/night.svg",
    textColor: "text-white",
    backgroundColor: "bg-gray-900",
    buttonColor: "bg-white",
    buttonText: "text-gray-900",
    borderColor: "border-gray-500",
    placeholderColor: "placeholder:text-gray-400",
    checkboxChecked: "bg-white/10 border-gray-400",
    checkboxUnchecked: "bg-transparent border-gray-600",
    checkboxText: "text-white",
    okButton: "bg-white text-gray-900",
  },
  {
    id: "pink-purple-theme",
    name: "Pink & Purple",
    backgroundImage: undefined,
    textColor: "text-purple-900",
    backgroundColor: "bg-purple-200",
    buttonColor: "bg-purple-900",
    buttonText: "text-white",
    borderColor: "border-purple-400",
    placeholderColor: "placeholder:text-purple-500/40",
    checkboxChecked: "bg-purple-300 border-purple-600",
    checkboxUnchecked: "bg-purple-200 border-purple-500",
    checkboxText: "text-purple-900",
    okButton: "bg-purple-900 text-white",
  },

  {
    id: "simple-elegant-background",
    name: "Simple Elegant Background",
    backgroundImage: "/bg/simple-elegant-bg.png",
    textColor: "text-[#B2734E]",
    backgroundColor: "bg-[#EDECE0]",
    buttonColor: "bg-[#B2734E]",
    buttonText: "text-white",
    borderColor: "border-[#B2744E]/40",
    placeholderColor: "placeholder:text-[#B2734E]/30",
    checkboxChecked: "bg-[#DFC8B7]/30  border-[#645d4f]",
    checkboxUnchecked: "bg-transparent border-[#645d4f]/40",
    checkboxText: "text-[EDECE0]",
    okButton: "bg-amber-900 text-white",
  },
];
