import type { Metadata } from "next";
import "@/app/globals.css";

import React from "react";
import {
  jost,
  mangericaRegular,
  poppins,
  quickSand,
  serifDisplay,
} from "@/utils/font";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function FormLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main
      className={`min-h-screen w-full h-full ${mangericaRegular.variable} ${jost.variable} ${poppins.variable}
              ${serifDisplay.variable} ${quickSand.variable}
              `}
    >
      {children}
    </main>
  );
}
