import { Toaster } from "@/components/ui/sonner";
import Provider from "@/provider";
import React from "react";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Provider>
          {children} <Toaster />
        </Provider>
      </body>
    </html>
  );
}
