import { Toaster } from "@/components/ui/sonner";
import Provider from "@/provider";
import {
  jost,
  libreBaskerville,
  lobster,
  mangericaRegular,
  playfairDisplay,
  poppins,
  prata,
  quickSand,
  roboto,
  serifDisplay,
  spaceGrotes,
} from "@/utils/font";
import "@/app/globals.css";
import React from "react";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <main
          className={`    
               ${mangericaRegular.variable} ${jost.variable} ${poppins.variable}
              ${serifDisplay.variable} ${quickSand.variable} ${libreBaskerville.variable} ${spaceGrotes.variable} ${prata.variable}
              ${lobster.variable} ${playfairDisplay.variable} ${roboto.variable}`}
        >
          <Provider>
            {children}
            <Toaster toastOptions={{}} richColors />
          </Provider>
        </main>
      </body>
    </html>
  );
}
