import type { Metadata } from "next";
import "@/app/globals.css";
import { ThemeProvider } from "@/components/ui/theme-provider";
import { Toaster } from "@/components/ui/sonner";
import React from "react";
import Navbar from "@/components/globals/navbar";
import Footer from "@/components/globals/footer";
import { mangericaRegular } from "@/utils/font";
import TanStackProvider from "@/provider/tanstack";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        {" "}
        <ThemeProvider
          attribute="class"
          defaultTheme="light"
          enableSystem
          disableTransitionOnChange
        >
          <TanStackProvider>
            <div
              className={`min-h-screen w-full h-full ${mangericaRegular.className} font-magericaRegular`}
            >
              <Navbar />
              {children}
              <Toaster toastOptions={{}} richColors />
              <Footer />
            </div>
          </TanStackProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
