import type { Metadata } from "next";
import "@/app/globals.css";
import { ThemeProvider } from "@/components/ui/theme-provider";
import { Toaster } from "@/components/ui/sonner";
import React from "react";
import Footer from "@/components/globals/footer";
import {
  jost,
  mangericaRegular,
  poppins,
  quickSand,
  serifDisplay,
} from "@/utils/font";
import TanStackProvider from "@/provider/tanstack";
import BuilderNavbar from "@/components/globals/navbar/builder-navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        {" "}
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <TanStackProvider>
            <div
              className={`min-h-screen antialiased max-w-full overflow-x-hidden h-full 
                
               ${mangericaRegular.variable} ${jost.variable} ${poppins.variable}
              ${serifDisplay.variable} ${quickSand.variable} font-magericaRegular`}
            >
              <BuilderNavbar />
              {children}
              <Toaster toastOptions={{}} richColors />
              <Footer />
            </div>
          </TanStackProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
