import type { Metadata } from "next";
import "@/app/globals.css";
import React from "react";

import BuilderNavbar from "@/components/globals/navbar/builder-navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div
      className={`min-h-screen antialiased max-w-full overflow-x-hidden h-full 
            font-magericaRegular`}
    >
      <BuilderNavbar />
      {children}

      {/* <Footer /> */}

      <div className="border-t border-border/40 md:flex md:items-center md:justify-center w-full">
        <p className="text-sm text-muted-foreground mt-8 md:mt-0 py-7">
          &copy; {new Date().getFullYear()} Formix INC. All rights reserved.
        </p>
      </div>
    </div>
  );
}
