import type { Metadata } from "next";
import "@/app/globals.css";
import { Toaster } from "@/components/ui/sonner";
import React from "react";
import {
  jost,
  mangericaRegular,
  poppins,
  quickSand,
  serifDisplay,
} from "@/utils/font";
import BuilderNavbar from "@/components/globals/navbar/builder-navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div
      className={`min-h-screen antialiased max-w-full overflow-x-hidden h-full 
                
               ${mangericaRegular.variable} ${jost.variable} ${poppins.variable}
              ${serifDisplay.variable} ${quickSand.variable} font-magericaRegular`}
    >
      <BuilderNavbar />
      {children}
      <Toaster toastOptions={{}} richColors />
      {/* <Footer /> */}

      <div className="border-t border-border/40 md:flex md:items-center md:justify-center w-full">
        <p className="text-sm text-muted-foreground mt-8 md:mt-0 py-7">
          &copy; {new Date().getFullYear()} Formix INC. All rights reserved.
        </p>
      </div>
    </div>
  );
}
